apiVersion: v1
kind: Service
metadata:
  name: python-nginx-postgres
  labels:
    app: python-nginx-postgres
spec:
  ports:
    - port: 5432
  selector:
    app: python-nginx-postgres
    tier: postgres
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: python-nginx-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python-nginx-postgres
  labels:
    app: python-nginx-postgres
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: python-nginx-postgres
        tier: postgres
    spec:
      containers:
      - image: postgres:latest
        name: postgres
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgres
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim
